application:
  version: 0.0.1
  title: Projeto base para estudos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    validate-on-migrate: true
    databaseType: mysql

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    packages:
      trust-all: true
    name-queue: fila.pessoa

server:
  port: 8081
  servlet:
    context-path: /api