application:
  version: 0.0.1
  title: Projeto que valida e produz um registros para ser consumido pela fila
spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    packages:
      trust-all: true
    name-queue: fila.pessoa

server:
  port: 8080
  servlet:
    context-path: /api