version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis-broker
    environment:
      - ARTEMIS_USERNAME=${ARTEMIS_USERNAME}
      - ARTEMIS_PASSWORD=${ARTEMIS_PASSWORD}
      - ARTEMIS_ROLE=admin
      - ARTEMIS_CLUSTER_USER=clusterUser
      - ARTEMIS_CLUSTER_PASSWORD=clusterPassword
      - ARTEMIS_CREATE_USER=true
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./save-broker:/var/lib/artemis-instance
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql-data:
  artemis-data:

networks:
  app-network:
    driver: bridge