version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  artemis:
    image: vromero/activemq-artemis
    container_name: artemis-broker
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
      - ANONYMOUS_LOGIN_ALLOWED=false
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - artemis-data:/var/lib/artemis-instance
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql-data:
  artemis-data:

networks:
  app-network:
    driver: bridge